cart/urls.py
from django.conf.urls import url
from . import views




urlpatterns = [


	url(r'^mycart/$', views.mycart, name="mycart"),

	url(r'^create_address/$', views.create_address, name="create_address"),
	url(r'^select_address/$', views.select_address, name="select_address"),
	url(r'^address_list/$', views.address_list, name="address_list"),
	url(r'^address_edit/(?P<slug>[-\w]+)/$', views.address_edit, name="address_edit"),
	url(r'^address_delete/(?P<slug>[-\w]+)/$', views.address_delete, name="address_delete"),

	url(r'^checkout/$', views.checkout, name="checkout"),




]

shop/urls.py
from django.conf.urls import url, include 
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bean/', include('coffee_bean.urls', namespace="coffee_bean")),
    url(r'^cart/', include('cart.urls', namespace="cart")),
    url(r'^payment/', include('payment.urls', namespace="payment")),
]

cart/models.py
from django.db import models
from coffee_bean.models import Coffee, Address
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save, post_delete
from decimal import Decimal


class CartItem(models.Model):
	cart = models.ForeignKey("Cart")
	items = models.ForeignKey(Coffee)
	quantitiy = models.PositiveIntegerField(default=1)
	line_item_total = models.DecimalField(max_digits=6, decimal_places=3)

	def __str__(self):
		return self.items.name

def cart_item_pre_save(sender, instance, *args, **kwargs):
	qty = instance.quantitiy
	if qty >= 1:
		price = instance.items.price
		total =  Decimal(price) * Decimal(qty)
		instance.line_item_total = total

pre_save.connect(cart_item_pre_save, sender=CartItem)

def cart_item_post_save(sender, instance, *args, **kwargs):
	instance.cart.update_subtotal()

post_save.connect(cart_item_post_save, sender=CartItem)
post_delete.connect(cart_item_post_save, sender=CartItem)

class Cart(models.Model):
	user = models.ForeignKey(User)
	items = models.ManyToManyField(Coffee, through=CartItem)
	subtotal = models.DecimalField(max_digits=6, decimal_places=3, default=2.000)
	delivery_total = models.DecimalField(max_digits=6, decimal_places=3, default=2.000)
	total = models.DecimalField(max_digits=6, decimal_places=3, default=2.000)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	
	def __str__(self):
		return self.user.username

	def update_subtotal(self):
		x = Decimal(0)
		items = self.cartitem_set.all()
		for item in items:
			x += Decimal(item.line_item_total)
		self.subtotal = Decimal(x)
		self.save()

def delivery_and_total(sender, instance, *args, **kwargs):
	subtotal = instance.subtotal
	delivery_total = Decimal(2.000)
	total = Decimal(subtotal) + Decimal(delivery_total)
	instance.delivery_total = Decimal(delivery_total)
	instance.total = Decimal(total)

pre_save.connect(delivery_and_total, sender=Cart)






class Order(models.Model):
	cart = models.ForeignKey(Cart)
	user = models.ForeignKey(User)
	address = models.ForeignKey(Address, null=True)

	def __str__(self):
		return self.user.username

cart/forms.py
from django import forms
from coffee_bean.models import Address

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = '__all__'
		exclude = ['user', 'slug']

class AddressSelectForm(forms.Form):
	address = forms.ModelChoiceField(
		queryset = Address.objects.all(),
		empty_label=None
		)

cart/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem, Order
from coffee_bean.models import Coffee, Address
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib import messages
from .forms import *



def mycart(request):
	cart, created = Cart.objects.get_or_create(user=request.user)

	item_id = request.GET.get("item")
	qty = request.GET.get("qty", 1)

	if item_id:
		coffee = Coffee.objects.get(id=item_id)
		cart_item, created = CartItem.objects.get_or_create(cart=cart, items=coffee)
		
		if int(qty)<1:
			cart_item.delete()
		else:
			cart_item.quantitiy = int(qty)
			cart_item.save()

	return render(request, 'cart.html', {'cart': cart})

############################################################################################

def create_address(request):
	form = AddressForm()
	if request.method == 'POST':
		form = AddressForm(request.POST)
		if form.is_valid():
			address = form.save(commit=False)
			address.user = request.user
			address.save()
			form.save()
			return redirect("cart:select_address")

	context = {
	"form": form
	}
	return render(request, 'create_address.html', context)

def select_address(request):
	if Address.objects.filter(user=request.user).count()<1:
		return redirect("cart:create_address")
	form = AddressSelectForm()
	form.fields['address'].queryset = Address.objects.filter(user=request.user)
	if request.method == 'POST':
		form = AddressSelectForm(request.POST)
		if form.is_valid():
			address = form.cleaned_data['address']
			order = Order.objects.get(user=request.user)
			order.address=address
			order.save()
			return redirect("cart:checkout")
	context = {
	'form':form

	}
	return render(request, 'select_address.html', context)


def address_list(request):
	username = request.user
	add_list = Address.objects.all().filter(user=username)
	context = {
		"add_list": add_list,
	}
	return render(request, 'address_list.html', context)


def address_edit(request, slug):
	address_obj = get_object_or_404(Address, slug=slug)
	form = AddressForm(request.POST or None, request.FILES or None, instance=address_obj)
	if form.is_valid():
		form.save()
		messages.success(request, "Address Updated!")
		return redirect("cart:address_list")
	context = {
		"form":form,
		"address_obj":address_obj,
	}
	return render(request, 'address_edit.html', context)


def address_delete(request, slug):
	obj = Address.objects.get(slug=slug).delete()
	messages.warning(request, "Address Deleted.")
	return redirect("cart:address_list")



############################################################################################



def checkout(request):
	cart, created = Cart.objects.get_or_create(user=request.user)
	order, created = Order.objects.get_or_create(cart=cart, user=request.user)

	if order.address == None:
		return redirect("cart:select_address")
	return redirect("payment:pay", order_id=order.id) #payment page

cart/templates/address_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Edit Address{% endblock head_title %}
{% block content %}


<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<form method="POST" action="{% url 'cart:address_edit' slug=address_obj.slug %}"enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
	
		<input type="submit" value="Edit address" class="btn btn-success">

	</form>
	</div>
</div>

{% endblock content %}

cart/templates/address_list.html
{% extends "base.html" %}

{% block head_title %}Address List{% endblock head_title %}

{% block content %}




<br>
<h1> My Address list </h1> <br>
<a href="{% url 'cart:create_address' %}" class="btn btn-default">Add Address</a>

<br>
<div class="row">
<div class="container">        
  <table class="table table-hover">
    <tbody>
     
      	{% for x in add_list %}
        <tr>
        <td><h4>{{x.name}}</h4></td>
        <td><a href="{% url 'cart:address_edit' slug=x.slug %}" class="btn btn-outline-primary">Edit Address</a></td>
        <td><a href="{% url 'cart:address_delete' slug=x.slug %}" class="btn btn-danger">Delete</a></td>
        </tr>
         {% endfor %}
         
    </tbody>
  </table>
</div>



  {% endblock content %}

cart/templates/cart.html
 {% extends "base.html" %}
{% load crispy_forms_tags %} 


{% block head_title %}My Cart{% endblock head_title %}
{% block content %}

<div class="row">
	<div class="col-md-12">
	{% if cart.cartitem_set.count < 1 %}
		<br><h1> Your cart is empty! <small> Please continue shoppping.</small></h1>
	{% else %}
		<br><h2>Your Cart: </h2>
		<table class= "table">
			<tr>
				<th>Item</th>
				<th></th>
				<th>Qty</th>
				<th>Price</th>
				<th>Delete item</th>
				{% for item in cart.cartitem_set.all %}
				<tr>
					<td>{{item.items.name}}</td>
					<td>
						<form action="{% url 'cart:mycart' %}" method="GET">
					      <input type="hidden" name="item" value="{{item.items.id}}">
					      <input type="number" name="qty" value="{{item.quantitiy}}">
					      <input type="submit" class="btn btn-outline-success" value="Update Item">
					     </form>
					</td>
					<td>{{item.quantitiy}}</td>
					<td>{{item.line_item_total}}</td>
					<td>
						<form action="{% url 'cart:mycart' %}" method="GET">
						<input type="hidden" name="item" value="{{item.items.id}}">
						<input type="hidden" name="qty" value="0">
						<input type="submit" class="btn btn-outline-danger" value="Delete Item">
					</form>
					</td>
				</tr>
			{% endfor %}
			<tr><td>Subtotal: {{cart.subtotal}} KD</td></tr>
			<tr><td>Delivery: {{cart.delivery_total}} KD</td></tr>
			<tr><td>Total: {{cart.total}} KD</td></tr>
			<tr><td><a href="{% url 'cart:checkout' %}" class="btn btn-success">Pay</a></td></tr>

		</table>
		{% endif %}
	</div>
</div>


{% endblock content %}

cart/templates/create_address.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 



{% block head_title %}Create Address{% endblock head_title %}
{% block content %}

<br><br>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<h1> Create Address </h1>
	<br><br>

	<form method="POST" action="{% url 'cart:create_address' %}" enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
		
	
		<input type="submit" value="Create Address"> <br><br>

	</form>
	</div>
	</div>


{% endblock content %}

cart/templates/select_address.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 



{% block head_title %}Select Address{% endblock head_title %}
{% block content %}

<br><br>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<h1> Select Address </h1>
	<br><br>

	<form method="POST" action="{% url 'cart:select_address' %}" enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
		
	
		<input type="submit" value="Select Address"> 
		<a href="{% url 'cart:create_address' %}" class="btn btn-default">Add Address</a>
		<br><br>
	</form>
	</div>
	</div>


{% endblock content %}