cart/urls.py
from django.conf.urls import url
from . import views




urlpatterns = [


	url(r'^mycart/$', views.mycart, name="mycart"),

	url(r'^create_address/$', views.create_address, name="create_address"),
	url(r'^select_address/$', views.select_address, name="select_address"),
	url(r'^address_list/$', views.address_list, name="address_list"),
	url(r'^address_edit/(?P<slug>[-\w]+)/$', views.address_edit, name="address_edit"),
	url(r'^address_delete/(?P<slug>[-\w]+)/$', views.address_delete, name="address_delete"),

	url(r'^checkout/$', views.checkout, name="checkout"),




]

coffee_bean/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [


	url(r'^signup/$', views.usersignup, name="signup"),
	url(r'^login/$', views.userlogin, name="login"),
	url(r'^logout/$', views.userlogout, name="logout"),

	url(r'^home/$', views.home, name="home"),
	url(r'^admin_home/$', views.admin_home, name="admin_home"),
	url(r'^user_home/$', views.user_home, name="user_home"),

	url(r'^bean_list/$', views.bean_list, name="bean_list"),
	url(r'^bean_create/$', views.bean_create, name="bean_create"),
	url(r'^bean_edit/(?P<slug>[-\w]+)/$', views.bean_edit, name="bean_edit"),
	url(r'^bean_detail/(?P<slug>[-\w]+)/$', views.bean_detail, name="bean_detail"),
	url(r'^bean_delete/(?P<slug>[-\w]+)/$', views.bean_delete, name="bean_delete"),

	url(r'^syrup_list/$', views.syrup_list, name="syrup_list"),
	url(r'^syrup_create/$', views.syrup_create, name="syrup_create"),
	url(r'^syrup_edit/(?P<slug>[-\w]+)/$', views.syrup_edit, name="syrup_edit"),
	url(r'^syrup_detail/(?P<slug>[-\w]+)/$', views.syrup_detail, name="syrup_detail"),
	url(r'^syrup_delete/(?P<slug>[-\w]+)/$', views.syrup_delete, name="syrup_delete"),

	url(r'^powder_list/$', views.powder_list, name="powder_list"),
	url(r'^powder_create/$', views.powder_create, name="powder_create"),
	url(r'^powder_edit/(?P<slug>[-\w]+)/$', views.powder_edit, name="powder_edit"),
	url(r'^powder_detail/(?P<slug>[-\w]+)/$', views.powder_detail, name="powder_detail"),
	url(r'^powder_delete/(?P<slug>[-\w]+)/$', views.powder_delete, name="powder_delete"),

	url(r'^roast_list/$', views.roast_list, name="roast_list"),
	url(r'^roast_create/$', views.roast_create, name="roast_create"),
	url(r'^roast_edit/(?P<slug>[-\w]+)/$', views.roast_edit, name="roast_edit"),
	url(r'^roast_delete/(?P<slug>[-\w]+)/$', views.roast_delete, name="roast_delete"),
	url(r'^roast_detail/(?P<slug>[-\w]+)/$', views.roast_detail, name="roast_detail"),

	url(r'^coffee_list/$', views.coffee_list, name="coffee_list"),
	url(r'^coffee_create/$', views.coffee_create, name="coffee_create"),
	url(r'^coffee_edit/(?P<slug>[-\w]+)/$', views.coffee_edit, name="coffee_edit"),
	url(r'^coffee_delete/(?P<slug>[-\w]+)/$', views.coffee_delete, name="coffee_delete"),
	url(r'^coffee_detail/(?P<slug>[-\w]+)/$', views.coffee_detail, name="coffee_detail"),
	url(r'^my_coffee/$', views.my_coffee, name="my_coffee"),


	# url(r'^address/$', views.address, name="address"),
	# url(r'^address_edit/(?P<slug>[-\w]+)/$', views.address_edit, name="address_edit"),
	# url(r'^address_list/$', views.address_list, name="address_list"),
	# url(r'^address_delete/(?P<slug>[-\w]+)/$', views.address_delete, name="address_delete"),



	url(r'^city_create/$', views.city_create, name="city_create"),
	url(r'^city_list/$', views.city_list, name="city_list"),
	url(r'^city_delete/(?P<slug>[-\w]+)/$', views.city_delete, name="city_delete"),




	url(r'^price_calculation/$', views.price_calculation, name="price_calculation"),

]

shop/urls.py
from django.conf.urls import url, include 
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bean/', include('coffee_bean.urls', namespace="coffee_bean")),
    url(r'^cart/', include('cart.urls', namespace="cart")),
    url(r'^payment/', include('payment.urls', namespace="payment")),
]

coffee_bean/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserSignUp(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password']

		widgets = {
		'password' : forms.PasswordInput()
		}



class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput()) 



class BeanForm(forms.ModelForm):
	class Meta:
		model = Bean
		fields = '__all__'

class SyrupForm(forms.ModelForm):
	class Meta:
		model = Syrup
		fields = ['name', 'price']

class PowderForm(forms.ModelForm):
	class Meta:
		model = Powder
		fields = ['name', 'price']

class RoastForm(forms.ModelForm):
	class Meta:
		model = Roast
		fields = ['name', 'price']


class CoffeeForm(forms.ModelForm):
	class Meta:
		model = Coffee
		fields = ['name','bean', 'roast', 'powder', 'syrup', 'water', 'foam', 'milk', 'shots', 'extra_instructions' ]
		#coffee = forms.MultipleChoiceField(Coffee.objects.all(), widget=forms.CheckboxSelectMultiple)

class CityForm(forms.ModelForm):
	class Meta:
		model = City
		fields = ['name']

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address
		fields = '__all__'
		exclude = ['user', 'slug']



    

coffee_bean/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import *
from django.contrib import messages
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404
from django.http import Http404, JsonResponse
from django.db.models import Q
from django.core.exceptions import ValidationError
from decimal import Decimal
from django.contrib.auth.models import User
import json


# Create your views here.



def usersignup(request):
	context = {}
	form = UserSignUp()
	context ['form'] = form 
	if request.method == "POST":
		form = UserSignUp(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			username = user.username
			password = user.password
			user.set_password(password)
			user.save()
			auth_user = authenticate(username=username, password=password)
			login(request, auth_user)

			return redirect("coffee_bean:home")
		messages.error(request, form.errors)
		return redirect("coffee_bean:signup")
	return render(request, 'signup.html', context)

def userlogout(request):
	logout(request)
	return redirect("coffee_bean:home")


def userlogin(request):
	context = {}
	form = UserLogin()
	context['form'] = form
	if request.method == "POST":
		form = UserLogin(request.POST)
		if form.is_valid():

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			auth_user = authenticate(username=username, password=password)
			if auth_user is not None:
				login(request, auth_user)
				return redirect("coffee_bean:coffee_list")

			messages.warning(request, "Wrong username/password combination. Please try again.")
			return redirect("coffee_bean:login")
		messages.error(request, form.errors)
		return redirect("coffee_bean:login")
	return render(request, 'login.html', context)



def home(request):
	return render(request, "welcome.html")

def admin_home(request):
	if not (request.user.is_staff or request.user.is_superuser):
		messages.warning(request, "Admin and Staff Only!")
		return redirect("coffee_bean:home") #change home to userhome later
	return render(request, "admin_home.html")


def user_home(request):
	return render(request, "coffee_list.html")




def bean_list(request):

	obj_list = Bean.objects.all()
	query = request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(name__icontains=query)
			).distinct()

	
	context = {
		"bean_list": obj_list,
		
	}
	return render(request, 'bean_list.html', context)



def bean_create(request):
	form = BeanForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request, "Bean created!")
		return redirect("coffee_bean:bean_list")
	context = {
		"form":form,
	}
	return render(request, 'bean_create.html', context)


def bean_edit(request, slug):
	bean_object = get_object_or_404(Bean, slug=slug)
	form = BeanForm(request.POST or None, request.FILES or None, instance=bean_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Bean Updated!")
		return redirect("coffee_bean:bean_list")
	context = {
		"form":form,
		"bean_object":bean_object,
	}
	return render(request, 'bean_edit.html', context)

def bean_detail(request, slug):
	obj =  get_object_or_404(Bean, slug=slug)
	username = request.user
	context = {
	"obj" : obj,
	"username" : username
	}
	return render(request, 'bean_detail.html', context)



def bean_delete(request, slug):
	obj = Bean.objects.get(slug=slug).delete()
	messages.warning(request, "Bean Deleted.")
	return redirect("coffee_bean:bean_list")



def syrup_list(request):

	obj_list = Syrup.objects.all()
	query = request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(name__icontains=query)
			).distinct()

	
	context = {
		"syrup_list": obj_list,
		
	}
	return render(request, 'syrup_list.html', context)



def syrup_create(request):
	form = SyrupForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request, "Syrup created!")
		return redirect("coffee_bean:syrup_list")
	context = {
		"form":form,
	}
	return render(request, 'syrup_create.html', context)


def syrup_edit(request, slug):
	syrup_object = get_object_or_404(Syrup, slug=slug)
	form = SyrupForm(request.POST or None, request.FILES or None, instance=syrup_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Syrup Updated!")
		return redirect("coffee_bean:syrup_list")
	context = {
		"form":form,
		"syrup_object":syrup_object,
	}
	return render(request, 'syrup_edit.html', context)

def syrup_detail(request, slug):
	obj =  get_object_or_404(Syrup, slug=slug)
	username = request.user
	context = {
	"obj" : obj,
	"username" : username
	}
	return render(request, 'syrup_detail.html', context)



def syrup_delete(request, slug):
	obj = Syrup.objects.get(slug=slug).delete()
	messages.warning(request, "Syrup Deleted.")
	return redirect("coffee_bean:syrup_list")



def powder_list(request):

	obj_list = Powder.objects.all()
	query = request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(name__icontains=query)
			).distinct()

	
	context = {
		"powder_list": obj_list,
		
	}
	return render(request, 'powder_list.html', context)



def powder_create(request):
	form = PowderForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request, "Powder created!")
		return redirect("coffee_bean:powder_list")
	context = {
		"form":form,
	}
	return render(request, 'powder_create.html', context)


def powder_edit(request, slug):
	syrup_object = get_object_or_404(Powder, slug=slug)
	form = PowderForm(request.POST or None, request.FILES or None, instance=powder_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Powder Updated!")
		return redirect("coffee_bean:powder_list")
	context = {
		"form":form,
		"powder_object":powder_object,
	}
	return render(request, 'powder_edit.html', context)

def powder_detail(request, slug):
	obj =  get_object_or_404(Powder, slug=slug)
	username = request.user
	context = {
	"obj" : obj,
	"username" : username
	}
	return render(request, 'powder_detail.html', context)



def powder_delete(request, slug):
	obj = Powder.objects.get(slug=slug).delete()
	messages.warning(request, "Powder Deleted.")
	return redirect("coffee_bean:powder_list")

def roast_list(request):

	obj_list = Roast.objects.all()
	query = request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(name__icontains=query)
			).distinct()

	
	context = {
		"roast_list": obj_list,
		
	}
	return render(request, 'roast_list.html', context)



def roast_create(request):
	form = RoastForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request, "Roast created!")
		return redirect("coffee_bean:roast_list")
	context = {
		"form":form,
	}
	return render(request, 'roast_create.html', context)


def roast_edit(request, slug):
	roast_object = get_object_or_404(Roast, slug=slug)
	form = RoastForm(request.POST or None, request.FILES or None, instance=roast_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Roast Updated!")
		return redirect("coffee_bean:roast_list")
	context = {
		"form":form,
		"roast_object":roast_object,
	}
	return render(request, 'roast_edit.html', context)

def roast_detail(request, slug):
	obj =  get_object_or_404(Roast, slug=slug)
	username = request.user
	context = {
	"obj" : obj,
	"username" : username
	}
	return render(request, 'roast_detail.html', context)



def roast_delete(request, slug):
	obj = Roast.objects.get(slug=slug).delete()
	messages.warning(request, "Roast Deleted.")
	return redirect("coffee_bean:roast_list")

def coffee_list(request):

	obj_list = Coffee.objects.all()
	query = request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(name__icontains=query)
			).distinct()

	
	context = {
		"coffee_list": obj_list,
		
	}
	return render(request, 'coffee_list.html', context)


def coffee_price (coffeetotal):
	total_price = coffeetotal.bean.price + coffeetotal.roast.price +(coffeetotal.shots*Decimal(0.250))
	if coffeetotal.milk:
		total_price+= Decimal(0.100)
	if coffeetotal.powder.all().count()>0:
		for powder in coffeetotal.powder.all():
			total_price+= powder.price
	if coffeetotal.syrup.all().count()>0:
		for syrup in coffeetotal.syrup.all():
			total_price+= syrup.price
	return total_price



def coffee_create(request):

	context = {}
	form = CoffeeForm()
	if request.method == "POST":
		form = CoffeeForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user
			obj.save()
			form.save_m2m()
			obj.price = coffee_price(obj)
			obj.save()

			messages.success(request, "Coffee created!")
			return redirect("coffee_bean:coffee_list")
	context = {
		'form':form
	}

	return render(request, 'coffee_create.html', context)



def coffee_edit(request, slug):
	coffee_object = get_object_or_404(Coffee, slug=slug)
	form = CoffeeForm(request.POST or None, request.FILES or None, instance=coffee_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Coffee Updated!")
		return redirect("coffee_bean:coffee_list")
	context = {
		"form":form,
		"coffee_object":coffee_object,
	}
	return render(request, 'coffee_edit.html', context)

def coffee_delete(request, slug):
	obj = Coffee.objects.get(slug=slug).delete()
	messages.warning(request, "Coffee Deleted.")
	return redirect("coffee_bean:coffee_list")

def coffee_detail(request, slug):
	obj =  get_object_or_404(Coffee, slug=slug)
	username = obj.user
	syrp = obj.syrup.all()
	powd = obj.powder.all()
	context = {
	"obj" : obj,
	"username" : username,
	"syrp": syrp,
	"powd": powd,
	}
	return render(request, 'coffee_detail.html', context)

coffee_bean/templates/admin_home.html
{% extends "base.html" %}


{% block head_title %}Admin{% endblock head_title %} 

{% block content %}



<div class="col-md-9 ">
<h1> Contents </h1>
<div><br><br>


<div class="row">
    <div class="col-md-6 ">
    <div class="thumbnail">
    <div class="caption">
    <center>
        {% if request.user.is_staff or request.user.is_superuser %}
        <p>
        <h2> Beans  
        <a href="{% url 'coffee_bean:bean_list' %}" class="btn btn-default">Go</a></h2>
        Add, Edit or Delete Beans
        <br><br>
        <h2> Syrups 
        <a href="{% url 'coffee_bean:syrup_list' %}" class="btn btn-default">Go</a></h2>
        Add, Edit or Delete Syrups
        <br><br>
        <h2> Powders 
        <a href="{% url 'coffee_bean:powder_list' %}" class="btn btn-default">Go</a></h2>
        Add, Edit or Delete Powders
        <br><br>
        <h2> Roasts
        <a href="{% url 'coffee_bean:roast_list' %}" class="btn btn-default">Go</a></h2>
        Add, Edit or Delete Roasts
        <br><br>
        </p>
        {% endif %}
    <center>
    </div>
    </div>
    </div>


    <div class="col-md-6">
    <center>
    <div class="thumbnail">
    <div class="caption">
        <p>
            <h2> Add Cities
            <a href="{% url 'coffee_bean:city_create' %}" class="btn btn-default">Go</a></h2>
            <h2> City List
            <a href="{% url 'coffee_bean:city_list' %}" class="btn btn-default">Go</a></h2>
        </p>
    <center>
    </div>
    </div>
    </div>
<div>


{% endblock %}

coffee_bean/templates/bean_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Edit Bean{% endblock head_title %}
{% block content %}


<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<form method="POST" action="{% url 'coffee_bean:bean_edit' slug=bean_object.slug %}"enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
	
		<input type="submit" value="Edit Bean" class="btn btn-success">

	</form>
	</div>
</div>

{% endblock content %}

coffee_bean/templates/coffee_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_title %}Coffee Detail{% endblock head_title %}

{% block content %}
<br><br>
	 <div class="col-sm-6 col-sm-offset-3 ">
		<div class="thumbnail">
			
			<h3>Name: {{obj.name}} || Price: {{obj.price}} </h3>
			Created By: {{obj.user}}
			<br><br>

			<ul>
			<li>Bean: {{obj.bean}}	</li>
			<li>Roast:	{{obj.roast}} </li>

			<li>Syrup(s): {% for x in syrp %} {{x}}, {% endfor %} </li>
			<li>Powder(s):	{% for y in powd %} {{y}}, {% endfor %} </li>

			<li>Water:	{{obj.water}} </li>
			<li>Foam:	{{obj.foam}} </li>
			<li>Steamed Milk: {{obj.milk}} </li>
			<li>Shots:	{{obj.shots}} </li>
			<li>Extra Instructions: {{obj.extra_instructions}}</li>
			</ul>



			<p>
			{% if request.user.is_staff or request.user.is_superuser or request.user == username %}
			
			<a href="{% url 'coffee_bean:coffee_edit' slug=obj.slug %}" class="btn btn-success">Edit</a>
			<a href="{% url 'coffee_bean:coffee_delete' slug=obj.slug %}" class="btn btn-danger">Delete</a>
			{% endif %}
			<a href="{% url 'coffee_bean:coffee_list' %}" class="btn btn-warning">Cancel</a>
			</p>
			
			<form action="{% url 'cart:mycart' %}" method="GET">
		      <input type="hidden" name="item" value="{{obj.id}}">
		      <input type="number" name="qty" value="1">
		      <input type="submit" name="btn btn-success" value="Add to cart">
		     </form>
			
		</div>
	</div>

{% endblock content %}

coffee_bean/templates/navbarpt2.html
	</ul>

	<ul class="navbar-nav my-2 my-lg-0">
	<li class="nav-item">
	<a class="nav-link" href="{% url 'cart:mycart' %}">My Cart</a>
	</li>


	  <li class="dropdown dropdown-menu-right">
		<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  {{request.user}}
		</a>
		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
		  <a class="dropdown-item" href="{% url 'coffee_bean:coffee_create' %}">Create Coffee</a>
		  <a class="dropdown-item" href="{% url 'coffee_bean:my_coffee' %}">My Coffee List</a>
		  <a class="dropdown-item" href="{% url 'cart:address_list' %}">My Address</a>
		  <div class="dropdown-divider"></div>
		  <a class="dropdown-item" href="{% url 'coffee_bean:logout' %}">Logout</a>
		</div>
	  </li>


		<li class="dropdown dropdown-menu-right">
		<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  Admin
		</a>
		{% if request.user.is_staff or request.user.is_superuser %}
		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
		  <a class="dropdown-item" href="{% url 'coffee_bean:admin_home' %}">Admin Home</a>
		  <div class="dropdown-divider"></div>
		  <a class="dropdown-item" href="{% url 'coffee_bean:bean_list' %}">Beans</a>
		  <a class="dropdown-item" href="{% url 'coffee_bean:syrup_list' %}">Syrups</a>
		  <a class="dropdown-item" href="{% url 'coffee_bean:powder_list' %}">Powders</a>
		  <a class="dropdown-item" href="{% url 'coffee_bean:roast_list' %}">Roasts</a>
		  <div class="dropdown-divider"></div>
		  <a class="dropdown-item" href="{% url 'coffee_bean:city_create' %}">add a city</a>
		</div>
		{% endif %}
	  </li>



	  </ul>
   </div>
</nav>

coffee_bean/templates/powder_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Edit Powder{% endblock head_title %}
{% block content %}


<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<form method="POST" action="{% url 'coffee_bean:powder_edit' slug=powder_object.slug %}"enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
	
		<input type="submit" value="Edit Powder" class="btn btn-success">

	</form>
	</div>
</div>

{% endblock content %}

coffee_bean/templates/powder_list.html
{% extends "base.html" %}


{% block head_title %}Powder List{% endblock head_title %}

{% block content %}



<br>
<h1> Powder List </h1>
<div class="row"><br>
{% for x in powder_list %}
  <div class="col-sm-6 ">
    <div class="thumbnail">
      <div class="caption">
        <h3>Powder: {{x.name}} Price: {{x.price}} </h3>
        
        <p>
        <a href="{{x.get_absolute_url}}" class="btn btn-primary">View</a> 
        
        <a href="{% url 'coffee_bean:powder_edit' slug=x.slug %}" class="btn btn-success">Edit</a>
        
        <a href="{% url 'coffee_bean:powder_delete' slug=x.slug %}" class="btn btn-danger">Delete</a>
		
        </p>
      </div>
    </div>
  </div>
 {% endfor %}
 {% endblock content %}


{% block form %}
      <form class="form-inline" action="{% url 'coffee_bean:powder_list' %}" method="Get">
      <a href="{% url 'coffee_bean:powder_create' %}" class="btn">Create Powder</a>
      <input class="form-control nav-buttons" type="text" name="q" placeholder="Search Powders Here" value="{{request.GET.q}}" aria-label="Search">
      <button class="btn btn-outline-success nav-buttons" type="submit">Search</button>
      <a href="?page={{ powder_list.number }}" class="btn btn-outline-success">Clear Search</a>
    </form>
{% endblock form %}

coffee_bean/templates/roast_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Roast Create{% endblock head_title %}
{% block content %}


<br><br>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<h1> Create Roast </h1>
	<br><br>

	<form method="POST" action="{% url 'coffee_bean:roast_create' %}" enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
		
	
		<input type="submit" value="Create Roast">

	</form>
	</div>
	</div>


{% endblock content %}

coffee_bean/templates/roast_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_title %}Roast Detail{% endblock head_title %}

{% block content %}


<br><br>
	 <div class="col-sm-6 col-sm-offset-3 ">
		<div class="thumbnail">
			
			<h3>Roast: {{obj.name}} Price: {{obj.price}} </h3>
			Added By: {{username}}
			<br>
			<p>
			<br>
			<a href="{% url 'coffee_bean:roast_edit' slug=obj.slug %}" class="btn btn-success">Edit</a>
			<a href="{% url 'coffee_bean:roast_delete' slug=obj.slug %}" class="btn btn-danger">Delete</a>
			<a href="{% url 'coffee_bean:roast_list' %}" class="btn btn-warning">Cancel</a>
			</p>
			
		</div>
	</div>

{% endblock content %}

coffee_bean/templates/roast_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block head_title %}Edit Roast{% endblock head_title %}
{% block content %}


<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<form method="POST" action="{% url 'coffee_bean:roast_edit' slug=roast_object.slug %}"enctype="multipart/form-data">

		{% csrf_token %}
		{{form|crispy}}
	
		<input type="submit" value="Edit Roast" class="btn btn-success">

	</form>
	</div>
</div>

{% endblock content %}

coffee_bean/templates/roast_list.html
{% extends "base.html" %}


{% block head_title %}Roast List{% endblock head_title %}

{% block content %}


<br>
<h1> Roast List </h1>
<br>
<div class="row">

{% for x in roast_list %}
  <div class="col-sm-6 ">
    <div class="thumbnail">
      <div class="caption">
        <h3>Roast: {{x.name}} Price: {{x.price}} </h3>
        
        <p>
        <a href="{{x.get_absolute_url}}" class="btn btn-primary">View</a> 
        
        <a href="{% url 'coffee_bean:roast_edit' slug=x.slug %}" class="btn btn-success">Edit</a>
        
        <a href="{% url 'coffee_bean:roast_delete' slug=x.slug %}" class="btn btn-danger">Delete</a>
		
        </p>
      </div>
    </div>
  </div>
 {% endfor %}
 {% endblock content %}


 {% block form %}
      <a href="{% url 'coffee_bean:roast_create' %}" class="btn">Create roast</a>
      <form class="form-inline" action="{% url 'coffee_bean:roast_list' %}" method="Get">
      <input class="form-control nav-buttons" type="text" name="q" placeholder="Search roasts Here" value="{{request.GET.q}}" aria-label="Search">
      <button class="btn btn-outline-success nav-buttons" type="submit">Search</button>
      <a href="?page={{ roast_list.number }}" class="btn btn-outline-success">Clear Search</a>
      
    </form>
{% endblock form %}